use soroban_sdk::{contractclient, Address, Env};

/// Cross-contract client generated by `#[contractclient]`.
/// The `OracleInterface` trait itself is only used to generate `OracleClient`;
/// suppress the dead-code lint on the trait.
#[allow(dead_code)]
#[contractclient(name = "OracleClient")]
pub trait OracleInterface {
    /// Returns the price of the asset in SMT (7 decimal places).
    fn get_price(e: Env, asset: Address) -> i128;
}
